version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: checklist_db
    environment:
      POSTGRES_USER: lucaf
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: checklist
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
